insert into address(addressName,streetName,aptNum,city,state,postalCode,username)
VALUES("Emmerich, Raynor and Paucek","0270 Valley Edge Drive","427","New York City","New York","10155","AugMo"),
("Mraz-Adams","2335 7th Circle","271","Cincinnati","Ohio","45213","SigMo"),
("Volkman-Romaguera","491 Transport Place","112","Punta Gorda","Florida","33982","CamGr"),
("Kemmer LLC","102 Brickson Park Parkway","199","Phoenix","Arizona","85020","FerGo"),
("Pacocha", "Dickens and O'Reilly","103 Petterle Trail","354","Washington","District of Columbia","20397","MagBa"),
("Thiel, Kihn and Mayert","716 Pepper Wood Park","230","Bozeman","Montana","59771","CarHi"),
("Toy-Zemlak","1725 Crownhardt Way","11","Orlando","Florida","32808","YetSa"),
("Kemmer, Weimann and Nolan","18 Maple Center","499","Winston Salem","North Carolina","27150","NicSh"),
("Vandervort-Doyle","5291 Talisman Terrace","210","Las Vegas","Nevada","89135","ChaCa"),
("Keeling-Hagenes","15353 Hanson Alley","186","Washington","District of Columbia","20319","AlyMe"),
("Jones, O'Connell and McLaughlin","40 Summit Center",NULL,"Loretto","Minnesota","55598","DexGa"),
("Langworth LLC","75 Helena Street",NULL,"New Haven","Connecticut","6520","PriBe"),
("King and Sons","3 Hovde Avenue",NULL,"Columbia","South Carolina","29225","LamDo"),
("Stracke-Stoltenberg","6 Bluejay Parkway",NULL,"Seattle","Washington","98133","KenMc"),
("Hackett, Mertz and Thompson","5 Mayer Crossing",NULL,"Richmond","Virginia","23208","ColLu"),
("Feest and Sons","697 Novick Junction",NULL,"Boca Raton","Florida","33499","CalTa"),
("Rogahn-Bosco","3 American Lane",NULL,"East Saint Louis","Illinois","62205","LisCa"),
("Balistreri-McCullough","5296 5th Junction",NULL,"Virginia Beach","Virginia","23464","LylHu"),
("Senger Inc","8286 Larry Point",NULL,"Washington","District of Columbia","20420","StuBr"),
("Cummerata-Considine","65664 Westridge Plaza",NULL,"El Paso","Texas","88558","DalBe");
